language: c++
os:
- linux
- osx
sudo: required
services:
- docker
git:
  depth: 1000000
env:
  global:
  - secure: "gFAgMSJEjy495VUpJr9c1TekDVoH11vcMvCHAkPeEaLkN8j7W+1vQqMYsMdxP88TTwPR3cl17mauVOpTnRSFpfjOb3TqbjRp1fmjyj1DOhXrR4sWkSN6nLdPTgrXFCgDZHKbxoVtkNXV16ZcVMPFNBdScmo2osl2PPQfoWpoV+Xf04/El/ISRKt7lA2hsDoTNxPqHmEDBcaHO80VnCYPAs4ucybiizDrhK5uiGjz2MGVEj9AuWDpZDK1e4BJYF9z9AJHn6Hek/L1+jM7BqHHKSIouarJkaZcjvHZ6v0DxIxTevsmpXCmuEMa5UbUaXGkgq8T2rJfVle2bG0Tgz+mw74F8NN6sJaawu0/TUY2NlkU5uwkqZzBIwZ4tKHGQ6uGJ/2+HhqqkmJdjfbkweRfwTpZQPv1KKODq8AzXCsFF8hXn5aJOyPeAo92PApDUaGY5HPMTEcwl36Bg6rVoGMyWa+j/pQ0gnMiqVZpaSzqAWqI9hEXk4ZSurQv+kgq1jXs4G2loOYtYIntNQXnmWR/oAtoXEXWS3aZjMQoy1f7M31Wr3hWyhkRn3eJai+g5eVwu/kcsvxJCBN0uE00rqWuC82ia1ZLqkhopSp9mtkpf4a4nV3ITnc6Fwb5qf/EjS95vBmelqNgGT6jF2AoNWqM9xBf6SlV3ghe0AHMr5ssZgg="
  - apiuser=joerghall
before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker build -t ubuntusourcesfs -f ${TRAVIS_BUILD_DIR}/buildtools/docker/ubuntu.docker
  buildtools/docker ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker build -t centossourcesfs -f ${TRAVIS_BUILD_DIR}/buildtools/docker/centos.docker
  buildtools/docker ; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then curl -L -O https://github.com/osxfuse/osxfuse/releases/download/osxfuse-3.6.3/osxfuse-3.6.3.dmg
  && ls -l *.dmg && hdiutil mount osxfuse-3.6.3.dmg && sudo installer -pkg /Volumes/FUSE\
  for\ macOS/FUSE\ for\ macOS.pkg -target / && hdiutil unmount /Volumes/FUSE\ for\
  macOS -quiet ; fi
script:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker run -v ${TRAVIS_BUILD_DIR}:/root/sourcesfs -e apikey -e apiuser -e TRAVIS_BRANCH
  --rm -t ubuntusourcesfs /bin/bash -c "mkdir /root/sourcesfs/build_ubuntu
  && cd /root/sourcesfs/build_ubuntu
  && echo $apiuser
  && cmake -DCMAKE_C_COMPILER=gcc-6 -DCMAKE_CXX_COMPILER=g++-6 -DCMAKE_BUILD_TYPE=Release ..
  && cmake --build .
  && cpack -G DEB
  && cmake --build . -- bintray_upload" ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker run -v ${TRAVIS_BUILD_DIR}:/root/sourcesfs -e apikey -e apiuser -e TRAVIS_BRANCH
  --rm -t centossourcesfs /bin/bash -c "mkdir /root/sourcesfs/build_centos
  && cd /root/sourcesfs/build_centos
  && echo $apiuser
  && cmake -DCMAKE_C_COMPILER=/opt/rh/devtoolset-6/root/usr/bin/gcc -DCMAKE_CXX_COMPILER=/opt/rh/devtoolset-6/root/usr/bin/g++ -DCMAKE_BUILD_TYPE=Release ..
  && cmake --build .
  && cpack -G RPM
  && cmake --build . -- bintray_upload" ; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then mkdir ${TRAVIS_BUILD_DIR}/build
  && echo $apiuser
  && cd ${TRAVIS_BUILD_DIR}/build && cmake ..
  && cmake --build .
  && cpack -G TGZ
  && cmake --build . -- bintray_upload ; fi
